restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
jobs: 300
max-jobs-per-second: 1
max-status-checks-per-second: 5
local-cores: 1
latency-wait: 60
keep-going: True
